application: guss
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /stylesheets
  static_dir: stylesheets
- url: /js
  static_dir: js
- url: /test.*
  script: gaeunit.app
- url: /install.*
  script: install.app
- url: /.*
  script: app.app

libraries:
- name: jinja2
  version: 2.6
- name: django
  version: 1.3

inbound_services:
- channel_presence
